services:
  gomaybelist:
    image: registry.gitlab.com/repository.host/go-maybe-list:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=cloud-public
        - traefik.http.routers.gomaybelist.entrypoints=websecure
        - traefik.http.routers.gomaybelist.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.gomaybelist.tls=true
        - traefik.http.routers.gomaybelist.tls.options=default
        - traefik.http.routers.gomaybelist.tls.certresolver=letsencrypt
        - traefik.http.routers.gomaybelist.middlewares=traefik-ratelimit,traefik-inflightreq,secureHeaders@file
        - traefik.http.services.gomaybelist.loadbalancer.server.port=4000
    networks:
      - cloud-public

networks:
  cloud-public:
    external: true
